- hack/go-fmt.sh
Fix `make fmt` so it works in CI. We can redo the local container version
later, if someone really needs it.
> go-fmt.sh: never run in a container

- hack/ci-test.sh
- hack/fetch_ext_bins.sh
We need a wrapper script to download and install kubebuilder because
the CI image doesn't include those tools. These scripts are copied
from the machine-api-operator repository.
> add tools for running unit tests in CI

- config/crd/bases/metal3.io_provisionings.yaml
We need to re-generate the provisioning CRD before CI's generate-check passes.
> Update the provisioning CRD generated by vendored controller-gen

- api/v1alpha1/provisioning_types.go
- config/crd/bases/metal3.io_provisionings.yaml
The grouping of the +kubebuilder comments was
causing the scope and subresource to not work.
> Bring the CRD closer to what it should be

- Makefile
- hack/gen-crd.sh
- hack/get-bmh-crd.sh
- hack/utils.sh
- manifests/0000_30_cluster-baremetal-operator_01_baremetalhost.crd.yaml
This PR adds the BaremetalHost CRD from openshift/baremetal-operator into the manifests directory. The file is renamed with the correct runlevel nomenclature required by the CVO.
> Add BMH CRD into manifests directory with appropriate run-level

- controllers/clusteroperator.go
- controllers/clusteroperator_test.go
- controllers/provisioning_controller.go
Set CO to Degraded state when provisioning CR validations fail
> Allow ClusterOperator to be set to Degraded state

- controllers/clusteroperator.go
- controllers/provisioning_controller.go
- provisioning/baremetal_config.go
Logging and then returning an error produces multiple messages, so
change a few spots to just return and let the caller do the logging.
Tighten up the language in a few log messages so they are shorter.
Wait until an action is done or failed to log, so we have "did action"
or "failed action" messages but no "doing action" messages. This
ensures that all of the information we need to have is in 1 log
message, instead of split across several.
> improve logging practices

- controllers/clusteroperator.go
- controllers/clusteroperator_test.go
This PR adds bmh as a relatedobject in the clusteroperator. This will enable the user to run:  `oc get -o yaml clusteroperator baremetal` and view that "baremetalhosts" is in the list of `relatedObjects`.
> Add bmh as a relatedobject in the clusteroperator

- controllers/clusteroperator.go
- controllers/clusteroperator_test.go
- controllers/provisioning_controller.go
This PR aims to implement the following logic.
```
0. When the cluster platform is NOT "baremetal", the ClusterOperator has status Progressing=false, Available=true, Disabled=true, Upgradeable=true, Degraded=false
When the cluster platform is "baremetal" and...
1. the Provisioning CR is valid and metal3 is being deployed, the ClusterOperator has status Progressing=true, Available=false, Disabled=false, Upgradeable=true, Degraded=false
2. the Provisioning CR is valid and metal3 is running, the ClusterOperator has status Progressing=false, Available=true, Disabled=false, Upgradeable=true, Degraded=false
3. the Provisioning CR is valid and metal3 has not successfully launched after 20 minutes, the ClusterOperator has status Progressing=true, Available=false, Disabled=false, Upgradeable=true, …
```
> Add correct condition states

- Makefile
- config/crd/bases/metal3.io_provisionings.yaml
- config/crd/patches/cainjection_in_provisionings.yaml
- config/crd/patches/webhook_in_provisionings.yaml
- hack/gen-crd.sh
- manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
Originally done to get "oc explain Provisioning" to print more information.
(https://bugzilla.redhat.com/show_bug.cgi?id=1880787)
Update:
So I think we should merge this, just because v1alpha1 is deprecated.. 
However this is not helping 'oc explain Provisioning'.
if I "oc apply -f manifests/0000_30_cluster-baremetal-operator_00_metal3provisioning.crd.yaml"
then 'oc explain Provisioning', I still get the same <empty> response.
> Generate the CRD with v1 (not v1alpha1)

- manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
- manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
- manifests/0000_31_cluster-baremetal-operator_03_baremetalhost.crd.yaml
- manifests/0000_31_cluster-baremetal-operator_04_serviceaccount.yaml
- manifests/0000_31_cluster-baremetal-operator_05_deployment.yaml
- manifests/0000_31_cluster-baremetal-operator_06_clusteroperator.cr.yaml
This is matches openshift/enhancements#414 and doesn't change existing behavior
> add current profile annotations to CVO manifests

- controllers/clusteroperator_test.go
- controllers/provisioning_controller.go
Baremetal CO should transition to Available state when a new Metal3
Deployment is applied successfully or when an existing Metal3 deployment
is found.
> Put CO in Available state

- Makefile
- go.mod
- vendor/modules.txt
This prevents strange build path errors like:
```
$ make lint
go build -o "bin/golangci-lint" ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint
without -mod=vendor, directory /home/.../go/src/github.com/openshift/cluster-baremetal-operator/vendor/github.com/golangci/golangci-lint/cmd/golangci-lint has no package path
make: *** [Makefile:62: bin/golangci-lint] Error 1
```
cc @asalkeld
> Set go version to 1.15 in go.mod

- Dockerfile
- controllers/clusteroperator.go
It looks like that the installation doesn't complete since the CBO ClusterOperator does not have an update Status.Version field, as required by CVO.
Enables also CVO integration
> Fix ClusterOperator Versions field and enable CBO integration

- Dockerfile
CBO wasn't tested with other platforms, which are now failing as CBO
doesn't become available. We need to fix that before reinstating the
label.
See: https://search.ci.openshift.org/?search=.*Cluster+operator+baremetal+is+still+updating.*&maxAge=48h&context=1&type=bug%2Bjunit&name=&maxMatches=5&maxBytes=20971520&groupBy=job
> Remove CBO from the release payload

- manifests/0000_31_cluster-baremetal-operator_03_baremetalhost.crd.yaml
The BareMetalHost CRD is missing the ErrorCount field, currently required by the BareMetal Operator
> Bug 1893832: add missing ErrorCount field

- Makefile
- controllers/provisioning_controller.go
- main.go
Add a command line option to specify the location of the file containing
the image references. This allows developers to use `make run` without
modifying files in /etc.
/cc @sadasu
> add -images-json command line option

- Dockerfile
- api/v1alpha1/provisioning_types.go
- config/rbac/role.yaml
- controllers/clusteroperator.go
- controllers/clusteroperator_test.go
- controllers/provisioning_controller.go
- controllers/provisioning_controller_test.go
- main.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
Current implementation sets the Baremetal CO to Disabled in Platforms other than BareMetal before starting the Reconciler.
Alternate approach: (re-worded based on @andfasano 's feedback below)
The CO manifest can be defined with the CO in Disabled state. So, when CVO installs all the manifests in the /manifest directory, the Baremetal CO starts in the Disabled state. On the BareMetal platform, the CO resource would be amended within the reconcile loop.
> Set Baremetal CO to Disabled before Reconciler runs

- manifests/0000_31_cluster-baremetal-operator_03_baremetalhost.crd.yaml
Add default value to BMH errorCount field to allow smoother upgrades.
Related to:
[1] https://github.com/metal3-io/baremetal-operator/pull/722
[2] https://github.com/openshift/machine-api-operator/pull/747
> Add default value to BMH errorCount field

- controllers/clusteroperator.go
- controllers/clusteroperator_test.go
- controllers/provisioning_controller.go
- controllers/provisioning_controller_test.go
- main.go
Avoid duplicating the logic for handling the disabled state by moving
the call to initialize the ClusterOperator from main into
SetupWithManager. That also lets us reuse the existing reconciler
method to set the ClusterOperator status, so we can eliminate
SetCOInDisabledState entirely.
This is a follow-up to #63
/cc @sadasu @asalkeld
> move logic for managing disabled state back inside the reconciler

- provisioning/baremetal_config.go
- provisioning/baremetal_config_test.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
This change makes the ironic containers get the hostIP when the
provisioningIP is blank. This removes the requirement for a
provisioningIP in Ironic, but additional work is needed to fix the image
URL's we pass to baremetal-operator.
As we are using an existing IP on an interface, we no longer have a
requirement on the static IP manager when the provisioningIP is blank,
so we do not start the containers in this case.
This also changes baremetal operator to communicate with the ironic
containers on localhost, as they are in the same pod.
> Use hostIP for ironic containers when provisionig network disabled 

- controllers/clusteroperator.go
The BMH relatedobject name should be an empty string. The relatedobject will be referenced like so:
Name.Resource.Group 
which can result in referencing an incorrect object.
> The bmh relatedobject name should be an empty string.

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
This adds the Ironic and Inspector log watching containers to the Metal3
deployment.  These are used to make the logs that baremetal hosts upload
to Ironic visible and collectable by OCP tools like `oc` and
`must-gather`.
> baremetal_pod: add log watcher containers

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
- provisioning/baremetal_pod.go
- provisioning/image_cache.go
- provisioning/provisioning_info.go
- provisioning/state_service.go
Add a cache for OS images accessible on port 6181 on every master node.
This cache downloads the images from the first-level cache in the metal3
Pod (port 6180). The images are kept in shared storage, so even when the
metal3 Pod moves, we'll never need to download them from the Internet
again.
The first few commits here are already proposed in #72.
> Add a second-level image cache

- controllers/clusteroperator.go
Without having the provisioning CRD set as a related resource, we aren't
collecting it in a must-gather.
After applying this PR and running a must-gather, we get the
provisioning CR in the must-gather:
```
./cluster-scoped-resources/metal3.io/provisionings/provisioning-configuration.yaml
```
> Bug 1905307: cluster-baremetal-operator: add provisioning CR as related object

- provisioning/baremetal_pod.go
Up to now we have relied on the ironic-static-ip-manager containers
managing the Provisioning IP to ensure that only one metal3 Pod is
started at a time. However, now that we support configurations without
such an IP, we should take other measures to ensure that we don't create
multiple inconsistent copies of the state (e.g. ironic database).
Changing the Deployment Strategy from the default rolling update to
recreate means that upon any changes to the Pod template, the existing
ReplicaSet will be deleted before an updated one is created.
> Bug 1866901: Don't do rolling updates of metal3 Deployment

- controllers/clusteroperator.go
- controllers/clusteroperator_test.go
- controllers/provisioning_controller.go
- provisioning/baremetal_pod.go
- provisioning/image_cache.go
- Create a new metal3 Deployment object and merge it with an existing one if available. The "merge" is done by ApplyDeployment(). As result of this, if the existing Deployment object was created by MAO (on upgrade from 4.6), the "cboOwnedAnnotation" would be added to the existing Deployment. If the Provisioning Config changed, then the DeploymentSpec would be updated with the DeploymentSpec of the new Deployment object that was created using the new config.
-  Use the state of the Deployment rollout to set the state in the "baremetal" ClusterOperator.
> Bug 1906105: Annotate existing metal3 deployment

- controllers/provisioning_controller.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_secrets.go
- provisioning/baremetal_secrets_test.go
- provisioning/image_cache.go
- provisioning/state_service.go
Delete all Secrets and the metal3 Deployment object created by the CBO when the Provisioning CR is deleted.
> Bug 1906935: Delete resources when Provisioning CR is deleted

- controllers/clusteroperator.go
- controllers/clusteroperator_test.go
- controllers/provisioning_controller.go
- go.mod
- go.sum
- provisioning/baremetal_pod.go
- provisioning/baremetal_secrets.go
- provisioning/container_images.go
- provisioning/image_cache.go
- provisioning/state_service.go
- vendor/github.com/stretchr/stew/slice/README.md
- vendor/github.com/stretchr/stew/slice/common.go
- vendor/github.com/stretchr/stew/slice/contains.go
- vendor/github.com/stretchr/stew/slice/doc.go
- vendor/github.com/stretchr/stew/slice/minus.go
- vendor/github.com/stretchr/stew/slice/plus.go
- vendor/modules.txt
@sadasu I hope you don't mind me tweaking code you have just written
- This only adds one dependency (stretchr/stew/slice - note we already use stretchr/testify)
- the other functions we already have vendored
/cc @sadasu
> Bug 1913716: Use existing libraries instead of rolling our own

- provisioning/baremetal_pod.go
The metal3 pod's toleration currently matches on
exact value matches only.
This can be confusing for some people as the vast
majority of our pods we use operator Exists, mean
any value can be specified. This
tolerations:
- effect: NoSchedule
key: node-role.kubernetes.io/master
This patch propose solution to add operator: Exists
- effect: NoSchedule
key: node-role.kubernetes.io/master
operator: Exists
This will make it easier for everyone to use this operator.
Closes BZ: #1900322
> Bug 1900322: Add Toleration OP Exists to metal3 pod

- Makefile
- config/cluster-baremetal-operator/kustomization.yaml
- config/crd/kustomization.yaml
- config/profiles/default/kustomization.yaml
- config/profiles/default/manager_auth_proxy_patch.yaml
- config/prometheus/alertrules.yaml
- config/prometheus/kustomization.yaml
- config/prometheus/proxyconfig.yaml
- config/prometheus/rbac.yaml
- config/prometheus/service.yaml
- config/rbac/kustomization.yaml
- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
- manifests/0000_31_cluster-baremetal-operator_03_service.yaml
- manifests/0000_31_cluster-baremetal-operator_05_kube-rbac-proxy-config.yaml
- manifests/0000_31_cluster-baremetal-operator_05_prometheus_rbac.yaml
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
- manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
- manifests/0000_90_cluster-baremetal-operator_03_servicemonitor.yaml
- manifests/0000_90_cluster-baremetal-operator_04_alertrules.yaml
- manifests/image-references
According to https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/operators.md#how-do-i-get-added-as-a-special-run-level, the certificate authority service is started at run level 09 and hence CBO's service monitor manifest should be created at that run level also.
For Prometheus to be able to scrape CBO metrics:
1. Added kubeProxyContainer to the CBO deployment
2. Created a ClusterIP Service (cluster-baremetal-operator-service) to expose CMO metrics port
3. Created a Service Monitor (cluster-baremetal-operator-servicemonitor) in order to be discovered automatically by the prometheus operator
4. Created ServiceAccount and Role with appropriate RBACs for prometheus to scrape CBO metrics endpoint
> Bug 1906102: Add standard metrics support for CBO

- provisioning/baremetal_config.go
- provisioning/baremetal_config_test.go
While deploying with IPv6, and with a provisioning network with subnet
other than /64 control plane hosts fails to PXE boot - this is due to
DNSmasq defaulting to /64. This updates the DHCP_RANGE environment
variable used by dnsmasq config specify the netmask.
This goes along with a similar installer PR: https://github.com/openshift/installer/pull/4639#issuecomment-776273143
> Bug 1927068: provisioning: configure DHCP range with netmask

- api/v1alpha1/provisioning_types.go
- config/crd/bases/metal3.io_provisionings.yaml
- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
- provisioning/baremetal_config_test.go
- provisioning/baremetal_pod.go
When the metal3 deployment is created, the BMO is not provided with
the WATCH_NAMESPACE env var which allows it to watch all Namespaces.
Also, change the rbacs to reflect the fact that BMH objects now can
exist in multiple namespaces and not just the openshift-machine-api
namespace.
> Allow BMO to watch all Namespaces

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_01_trusted-ca-configmap.yaml
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/image_cache.go
- provisioning/provisioning_info.go
This mounts the trusted CA bundle, and reads and injects the proxy
configuration into all of our containers. This is somewhat based off
what machine-api-operator does. This is because the "cluster-wide" proxy
configuration is not truly clsuter-wide, and we have to inject this
variables ourselves. We also inject the trusted CA bundle, as it's likely
many users have custom CA's in use for their TLS certificates.
> Bug 1885349: Inject proxy environment variables everywhere

- Makefile
Allow us to use the env variable $IMAGES_JSON if set,
if not then default to the /etc/cluster-baremetal-operator
value. With this we can set the value in dev-scripts/metal3-dev/local-cbo.sh
> Only set IMAGES_JSON if not previously set

- manifests/0000_31_cluster-baremetal-operator_03_baremetalhost.crd.yaml
This is to align with the rebase proposed via:
https://github.com/openshift/baremetal-operator/pull/133
> Update BMH CRD

- provisioning/baremetal_pod.go
Ensure WATCH_NAMESPACE is always set whether enabled or not.
> Ensure WATCH_NAMESPACE is always set whether enabled or not

- provisioning/baremetal_crypto.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_secrets.go
- provisioning/baremetal_secrets_test.go
In updateTlsSecret() we do the following check:
```
existingCert := secret.StringData[corev1.TLSCertKey]
if existingCert != "" {
```
This should always fail as StringData is WriteOnly. This will result in continuous writes to the secret (that we are watching).
Note: from the godoc
```
// stringData allows specifying non-binary secret data in string form.
// It is provided as a write-only convenience method.
// All keys and values are merged into the data field on write, overwriting any existing values.
// It is never output when reading from the API.
// +k8s:conversion-gen=false
// +optional
StringData map[string]string `json:"stringData,omitempty" protobuf:"bytes,4,rep,name=stringData"`
```
/cc @stbenjam 
This maybe contributing to the secret watch issue.
> Bug 1948787: secret.StringData is a WriteOnly convience field, stop using it to read

- config/cluster-baremetal-operator/cluster-baremetal-operator.yaml
- config/profiles/default/manager_auth_proxy_patch.yaml
- config/profiles/default/manager_webhook_patch.yaml
- manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
- provisioning/baremetal_pod.go
- provisioning/image_cache.go
In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
> Add management workload annotations

- config/cluster-baremetal-operator/cluster-baremetal-operator.yaml
- config/profiles/default/manager_auth_proxy_patch.yaml
- config/profiles/default/manager_webhook_patch.yaml
- manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
- provisioning/baremetal_pod.go
As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged please
> Rename workload annotations

- provisioning/baremetal_pod.go
Set the env variable WEBSERVER_CACERT_FILE which is used by Ironic
for the ironic.conf setting ``webserver_verify_ca``.
> Bug 1953795: Set Ironic webserver_verify_ca

- provisioning/baremetal_pod.go
The staticIPManager container is not required when the ProvisioningNetwork
is Disabled or the ProvisioningIP is not provided.
> Bug 1952448: Update condition for starting the metal3StaticIpManager container

- provisioning/baremetal_pod.go
Reverts openshift/cluster-baremetal-operator#139
This is the wrong cert to use for the assisted images, it uses the service ca, this needs more investigation in another release to make the service, ingress, and trusted CA bundles available to our containers, as well as investigating using TLS for the httpd hosted by Ironic.
> Revert "Bug 1953795: Set Ironic webserver_verify_ca"

- config/crd/bases/metal3.io_provisionings.yaml
IPv6 provisioning networks cannot be larger than a /64 due to a limitation in dnsmasq.
> Bug 1947293: Document ipv6 provisioning network size limitation

- provisioning/image_cache.go
By default cluster.local is part of NoProxy, using the longer
version ensure we match the NoProxy variable and keep the traffic
internal.
Fixes: https://github.com/openshift/cluster-network-operator/issues/1105
> Bug 1962592: Use a cache URL with the .svc.cluster.local suffix

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
The staticIPManager container should be run when the Provisioning
Network is not Disabled and the ProvisioningIP is provided.
> Bug 1952448: Fix condition for starting the metal3StaticIpManager container

- provisioning/baremetal_pod.go
- provisioning/image_cache.go
According to the [openshift conventions document][0], all control plane
pods must set memory and cpu resource requests, and must not set limits.
The cluster baremetal operator currently doesn't set either.
The challenge lies less in setting those values but more in determining
suitable values.  The metal3 pod started by the CBO consists of the
following containers:
* metal3-baremetal-operator
* metal3-mariadb
* metal3-httpd
* metal3-ironic-conductor
* ironic-inspector-ramdisk-logs
* metal3-ironic-api
* ironic-deploy-ramdisk-logs
* metal3-ironic-inspector
* metal3-static-ip-manager
* metal3-dnsmasq
In order to determine suitable resource requests, we will query the
in-cluster instance of Prometheus.  The two queries are:
* `container_memory_working_set_bytes`
* …
> Bug 1940518: Set default resource requests for all containers

- controllers/provisioning_controller.go
- provisioning/baremetal_config.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/image_cache.go
- provisioning/provisioning_info.go
This should be equal to
"ip=dhcp" (when ipv4 only)
"ip=dhcp6" (when ipv6 only)
"" (when dual stack)
the downloader will then do the following
```
if [ -n "$IP_OPTIONS" ] ; then
LIBGUESTFS_BACKEND=direct virt-edit -a "$RHCOS_IMAGE_FILENAME_QCOW" -m /dev/sda3 /boot/loader/entries/ostree-1-rhcos.conf -e "s/^options/options ${IP_OPTIONS}/"
fi
```
/cc @sadasu @honza 
This is an alternative to https://github.com/openshift/cluster-baremetal-operator/pull/143
> Bug 1946079: pass IP_OPTIONS env down to the OS downloader container

- main.go
Previously CBO was watching over all the namespaces, thus caching all the resources with an high memory consumption (even those ones that didn't really belong to the component)
This PR fixes the issue by limiting the cache just to the component namespace `openshift-machine-api` (updates on cluster scoped resources as `Provisioning` will be received as usual)
Fixes #1968615
> Bug 1968615: Restrict watches to openshift-machine-api

- provisioning/baremetal_pod.go
Currently ironicTlsMount and inspectorTlsMount are missing from
baremetal pod definition. This may cause TLS issues while attempting
unmanaged inspection. This change adds those properties.
> Bug 1968701: Add ironic/inspector TlsMounts to baremetal pod

- controllers/provisioning_controller.go
- controllers/provisioning_controller_test.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/provisioning_info.go
There was at least 3 things wrong with how we figure out the NetworkStack
1. the NetworkStack enum was broken - blush
2. we were assuming that when len(ip) == IPv6Len it was an actual ipv6 address (you can have an embedded ipv4 address in a v6 one - news to me)
3. this is now using the internal apiserver url not, the public one
See https://github.com/openshift/ironic-rhcos-downloader/pull/40#issuecomment-858206600
This PR supersedes https://github.com/openshift/cluster-baremetal-operator/pull/154
and includes @sadasu commit in her PR https://github.com/openshift/cluster-baremetal-operator/pull/157
/cc @sadasu @honza @andfasano
> Bug 1946079: Fix network stack calculation

- provisioning/baremetal_pod.go
- provisioning/image_cache.go
We only want to pass the IP_OPTIONS environment variable to the
machine-os-downloader container in the metal3 Deployment, not the ones
in the metal3-image-cache DaemonSet.
If we pass it to both then the options get added twice on some cache
Pods (the ones not running on the Node that has the API VIP), with the
result that the checksum will be different depending where the API VIP
is pointing.
> Don't set IP options on kernel command line twice

- config/cluster-baremetal-operator/cluster-baremetal-operator.yaml
- config/profiles/default/manager_auth_proxy_patch.yaml
- manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
- manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
- manifests/image-references
- provisioning/container_images_test.go
- provisioning/sample_images.json
The old registry.svc.ci.openshift.org is deprecated and will be removed
soon
> Use new registry registry.ci.openshift.org

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
Only add metal3-static-ip-set if we have a provisioning ip and
and provisioning network is enabled. This brings the check for
both metal3-static-ip-set and metal3-static-ip-manager inline
with each other. It doesn't make sense to have one without the
other.
> Bug 1972753: Only start static ip set if provisioning net not disabled

- api/v1alpha1/provisioning_types.go
- config/crd/bases/metal3.io_provisionings.yaml
- manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
- provisioning/baremetal_config.go
Allow setting the source boot iso parameter to enable or disable local
caching of the boot iso image.
> Allow boot iso source configuration

- provisioning/baremetal_pod.go
> Bug 1973724: reorder the initContainers, so that static-ip-set happens prior to the image download

- manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/container_images.go
- provisioning/container_images_test.go
This PR prepares CBO to accomodate the migration of Ironic Inspector into the Ironic image. 
Requires https://github.com/metal3-io/ironic-image/pull/253, https://github.com/openshift/ironic-image/pull/179
> Use ironic image for ironic-inspector

- api/v1alpha1/provisioning_types.go
- api/v1alpha1/provisioning_validation.go
- config/crd/bases/metal3.io_provisionings.yaml
- manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
Validate that managed ipv6 provisioning networks are no larger than a
/64 due to a dnsmasq limitation, also add some relevant documentation.
> Bug: 1947293 Add managed provisioning network size validation

- provisioning/image_cache.go
By default cluster.local is part of NoProxy, using the longer
version ensure we match the NoProxy variable and keep the traffic
internal.
Backports:https://github.com/openshift/cluster-baremetal-operator/pull/147
> [release-4.7] Bug 1972291: Use a cache URL with the .svc.cluster.local suffix

- provisioning/baremetal_pod.go
If VirtualMediaViaExternalNetwork is set and the ProvisioningNetwork
is not Disabled, remote workers on the external network need to use
the host IP of the master node on the external network to talk back to
Ironic.
> Pass IRONIC_EXTERNAL_IP to Ironic container

- provisioning/baremetal_pod.go
We need to set this for ironic conductor also as it is the thing
responsible for setting up the callback.
> Set external IP env var for ironic conductor too.

- provisioning/baremetal_pod.go
This PR fixes the port conflicts recently discovered on CI between metal3 cluster-cloud-controller-manager-operator: both are using the default port for the health endpoint `9440`, and both are using the host network. Since cccmo is usually deployed first by CVO, when both deployments land on the same node then metal3 won't start.
> Customize metal3 health endpoint to avoid port conflicts

- provisioning/baremetal_secrets.go
Currently we are sending the pull secret as a plain string to the Configure-CoreOS init container. The ironic image expects the data to be in base64 encoded string.
See: https://github.com/openshift/ironic-image/blob/7694a8a2fdadf0e9e303b9d9c9003a70bc7b3753/ironic-config/ironic-python-agent.ign.j2#L53
> Bug 1986464: Send pull secret data as base64 encoded string

- controllers/provisioning_controller.go
- provisioning/baremetal_config.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/image_cache.go
- provisioning/provisioning_info.go
This is a squashed backport of the following commits
- https://github.com/openshift/cluster-baremetal-operator/commit/da0fdb5627d71ed60bcc1a5dfac8e9360b0d33a1
- https://github.com/openshift/cluster-baremetal-operator/commit/126f94f94e0d2720a49e149f57a6e2ec31e0bf33
- https://github.com/openshift/cluster-baremetal-operator/commit/5d37ad30322b511361c352ade461c96f5540190b
- https://github.com/openshift/cluster-baremetal-operator/commit/4589e4c490154ea20d6b28c69283ce3a6efd278f
- https://github.com/openshift/cluster-baremetal-operator/commit/9073a729a3a90d94d84be3f5baa8e0449c29aa41
- https://github.com/openshift/cluster-baremetal-operator/commit/392448754b540c995f13b05884d22ab0fc75428c
> [release-4.7] Bug 1973367: Pass IP_OPTIONS=dhcp|dhcp6 down to OS Downloader container

- provisioning/baremetal_config_test.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
When specifying both PreProvisioningOSDownloadURLs and ProvisioningOSDownloadURL in the provisioning config CR, CBO will fail to reconcile becasuse two copies of machine-os-downloader init containers with the same name are started. The names of these initcontainers should be different when both of them are spawned together.
> Bug 1986462: Separate the names of machine os downloader when two copies are started 

- manifests/image-references
- provisioning/sample_images.json
The ironic-inspector service was deprecated in 4.9 and removed
in 4.10, we need to use the ironic image as reference.
In #132 we switched to use use the ironic image, now we need to remove the old reference.
> Remove ironic-inspector reference in CBO

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
Only add metal3-static-ip-set if we have a provisioning ip and
and provisioning network is enabled. This brings the check for
both metal3-static-ip-set and metal3-static-ip-manager inline
with each other. It doesn't make sense to have one without the
other.
> Bug 1975711: Only start static ip set if provisioning net not disabled

- controllers/clusteroperator.go
- controllers/clusteroperator_test.go
- controllers/provisioning_controller.go
- Make the state of a missing CR more explicit by creating a ```ReasonProvisioningCRNotFound```.
- Fix a code path when this was not set.
- Remove the ownership on the clusterOperator as it was both ineffective and possibly not desired.
/cc @sadasu
> Bug 1991641: make provisioning CR status more explicit and remove the ownership on the CO

- provisioning/baremetal_pod.go
Enable the functionality to set force_persistent_boot_device
to "Never" for live ISO nodes. This will allow nodes to be
booted once to CD then rebooted to HD.
> Bug 2000445: Set LIVE_ISO_FORCE_PERSISTENT_BOOT_DEVICE=Never

- api/v1alpha1/provisioning_validation_test.go
Explicitly verify that validation fails if the ProvisioningIP is
missing, unless the Provisioning network is disabled.
> Add tests for missing ProvisioningIP in validation

- provisioning/baremetal_config.go
- provisioning/baremetal_webhook_test.go
This PR changes validatingwebhook port from 9443 to 9447. Because
9443 is generic port and might cause conflicts and moreover,
according to https://github.com/openshift/enhancements/blob/master/dev-guide/host-port-registry.md
it is used by kube-controller-manager.
> Change BMO validatingwebhook port to 9447

- README.md
- api/v1alpha1/provisioning_types.go
- config/crd/bases/metal3.io_provisionings.yaml
- manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
- provisioning/baremetal_config.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/state_service.go
Especially in the live ISO case, the virtual media images may contain
sensitive information. Now that we've established that Redfish hardware
does not verify TLS certificates, we can use our self-signed certificate
to protect the communication with the BMC.
A knob to turn this feature off is provided for hardware that diverges.
Requires:
- https://github.com/openshift/ironic-image/pull/218
- https://github.com/openshift/enhancements/pull/917
- https://github.com/openshift-metal3/dev-scripts/pull/1301
> Serve virtual media ISOs over TLS

- controllers/clusteroperator.go
- controllers/provisioning_controller.go
Updating the CO status message added as part of https://github.com/openshift/cluster-baremetal-operator/pull/191
> Bug 1991641: Fix CO message when Provisioning CR is not present

- controllers/provisioning_controller.go
- main.go
This PR adds additional check to not enable `ValidatingWebhookConfiguration` for non baremetal platforms like AWS, Azure, GCP. Because Cluster Baremetal Operator is already disabled in these platforms.
> Bug 2024900: Not enable CBO webhook in unsupported platform

- api/v1alpha1/provisioning_validation.go
- api/v1alpha1/provisioning_validation_test.go
- controllers/clusteroperator_test.go
In future we will provision with the CoreOS installer, so we won't need
a ProvisioningOSDownloadURL. Stop enforcing its presence in the webhook.
> Make ProvisioningOSDownloadURL optional

- manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
- manifests/image-references
- provisioning/container_images.go
- provisioning/container_images_test.go
- provisioning/sample_images.json
The image-customization-controller will not be added to the release payload until it is referenced in the images configmap of CBO. (Or alternatively has the label `io.openshift.release.operator=true` applied.)
This patch is part of #208, but we want the installer change https://github.com/openshift/installer/pull/5425 to land first. It cannot do so unless the image-customization-controller is in the release payload.
We have successfully built an image in OSBS:
```
ose-image-customization-controller-container-v4.10.0-202112102123.p0.gfaf44b3.assembly.stream successfully tagged into rhaos-4.10-rhel-8-candidate by osbs
```
> Add the image-customization controller to the images configmap

- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
- manifests/image-references
- provisioning/baremetal_config.go
- provisioning/baremetal_config_test.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/container_images.go
- provisioning/container_images_test.go
- provisioning/image_cache.go
- provisioning/image_customization.go
- provisioning/image_customization_service.go
- provisioning/machine_os_images.go
- provisioning/sample_images.json
When the Provisioning Network is not being used (ProvisioningNetwork=Disabled or ProvisioningNetwork=Enabled and VirtualMediaViaExternalNetwork = true), the image customization controller deployment uses the host IP of the master on which metal3 deployment is running as the IP address of Ironic.
When the metal3 deployment moves to a different master, we need to make sure that the metal3-image-customization deployment uses this new host IP as Ironic's IP address.
CBO already watches for changes in the Deployment() resource and when the metal3 deployment moves, a reconcile loop would be triggered, Ironic's IP will once again be evaluated and the metal3-image-customization deployment will be updated with this new IP. 
Co-Authored-By: Zane Bitter zbitter@redhat.com
> Start image customization controller

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
- provisioning/baremetal_pod.go
To extract pod's host IP address, CBO tries to list pods in here https://github.com/openshift/cluster-baremetal-operator/blob/b7bba707a8d6c3a3e6b63dc75afdf93ec60183a1/provisioning/baremetal_pod.go#L1071
However, CBO does not have allowance to list pods. This PR adds this.
> Bug 2035239: Add pod listing permission to extract pod host IP

- provisioning/baremetal_pod.go
- provisioning/image_customization.go
Even if there is no metal3 Pod up and therefore we cannot find its IP
address, we still want to create the image-customization-controller with
an empty ironic IP address.
This is documented in a comment at the site where getPodHostIP() is
called, but not in the implementation, so it was inadvertently broken
by #225.
>  Bug 2038272: Create image-customization-controller when metal3 Pod not up

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
CBO should be able to list the Pods running in the openshift-machine-api namespace to determine the Pod's IP to create the i-c-c deployment. Also, removing CBO's cluster wide permissions to get and list Pods.
> Bug 2037483: Allow CBO to list Pods only in the openshift-machine-api namespace

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/image_customization.go
- provisioning/machine_os_images.go
The installed CoreOS that is written to disk needs IP options set such that it can contact the MCO over the external network to obtain the Ignition file for the Machine.
These options may be different from the ones needed for pre-provisioning, when IPA has to contact ironic, usually over the provisioning network.
Pass the option to the image-customization-controller, so it can build it into the IPA ignition (in https://github.com/openshift/image-customization-controller/pull/31)
> Bug 2034527: Pass IP options to installed CoreOS image

- provisioning/image_customization.go
Pass the proxy when starting the image-customization-controller container.
Avoid the issue that ironic agent image cannot be downloaded due to network proxy.
See https://github.com/openshift/installer/issues/5552 for details.
Signed-off-by: Zhou Hao <zhouhao@fujitsu.com>
> Bug 2045927: Add proxy for image-customization-controller

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/image_customization.go
- provisioning/machine_os_images.go
- provisioning/provisioning_info.go
- provisioning/provisioning_info_test.go
- provisioning/utils.go
To start an agent image, the assisted service needs to know the Ironic
URL and kernel parameters. This change makes the corresponding functions
public, moves them to a new utils.go and detaches from ProvisioningInfo.
> Extract functions for ZTP integration

- provisioning/baremetal_pod.go
Update the way metal3 Deployment status is reported using guidance from : https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#complete-deployment
The earlier implementation assumed only one Deployment Status Condition could be true at a time. This resulted in the metal3 deployment status being reported incorrectly and as a consequence, the "baremetal" ClusterOperator was reporting the wrong status.
> Bug 2088428: Fix interpretation of Deployment Status Conditions

- provisioning/baremetal_pod.go
This is 4.9 cherry pick of https://github.com/openshift/cluster-baremetal-operator/pull/266
(cherry picked from commit 30c2b9a92ddb78cd2275c2bb27e37fd49fc96849)
> [release-4.9] Bug 2091747: Fix interpretation of Deployment Status Conditions

- Makefile
- config/profiles/default/manager_auth_proxy_patch.yaml
- config/prometheus/proxyconfig.yaml
- manifests/0000_31_cluster-baremetal-operator_05_baremetal-kube-rbac-proxy-config.yaml
- manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
The MAO already supplies a resource called `kube-rbac-proxy`, so we want
ours to be unique.
> Bug 2084215: Add baremetal prefix to kube-rbac-proxy

- Makefile
- hack/ci-test.sh
- hack/generate.sh
- hack/get-bmh-crd.sh
- hack/utils.sh
* Use portable shebangs
* Don't cd into GOPATH dir in hack/generate.sh
* Remove a cyclic dependency in Makefile
> Fix a few papercuts

- controllers/provisioning_controller.go
- provisioning/baremetal_config.go
- provisioning/baremetal_config_test.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/image_cache.go
- provisioning/image_customization.go
- provisioning/machine_os_images.go
* Move the machine-os-images init container from cache to ICC
* Disable the cache if ProvisioningOSDownloadURL is empty
* Do not report cache state if it is disabled
> METAL-157: Don't run image cache unless required

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- controllers/provisioning_controller_test.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
We're currently detecting control plane nodes by "master" in their BMH
names. This is not reliable. Use a nodes filter instead.
> OCPBUGS-421: do not rely on string "master" to be in BMH names

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- controllers/provisioning_controller_test.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
We're currently detecting control plane nodes by "master" in their BMH
names. This is not reliable. Use a nodes filter instead.
(cherry picked from commit b9a929a9f3fb82ca47a7482adea655d88aefe935)
> OCPBUGS-747: do not rely on string "master" to be in BMH names

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- controllers/provisioning_controller_test.go
- main.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
Apparently, NodeSpec.ProviderID may not be populated until CAPBM
gets to it. Which may not happen if BMO does not start.
Solve this chicken-and-egg problem by listing machines instead.
> OCPBUGS-1806: Use machines instead of nodes to detect masters

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- controllers/provisioning_controller_test.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
We're currently detecting control plane nodes by "master" in their BMH
names. This is not reliable. Use a nodes filter instead.
(cherry picked from commit b9a929a9f3fb82ca47a7482adea655d88aefe935)
> OCPBUGS-1239: do not rely on string "master" to be in BMH names

- controllers/provisioning_controller.go
Some deployments don't have Machines or master BareMetalHosts.
Fall back to the old behavior (= not setting PROVISIONING_MACS).
> OCPBUGS-4689: Do not fail the reconciler when no master Machines exist

- README.md
- api/v1alpha1/provisioning_types.go
- config/crd/bases/metal3.io_provisionings.yaml
- manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
- provisioning/baremetal_config.go
- provisioning/baremetal_config_test.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
In the ZTP case, we need DNS on the provisioning network, so that
the CoreOS root filesystem can be downloaded from the cluster.
> OCPBUGS-1844: enable DNS in the provisioning dnsmasq

- controllers/provisioning_controller.go
- provisioning/image_cache.go
Keeping ironic-proxy active (e.g. when switching from provisioning
network Disabled to Managed) causes a conflict with the metal3 pod.
> OCPBUGS-4712: delete ironic-proxy/image-cache when not needed

- controllers/provisioning_controller.go
- controllers/provisioning_controller_test.go
This is the 3rd attempt to fix the race when determining, which MAC
addresses the master nodes have.
In the 2nd attempt, we started using annotations on Machines that link
to BareMetalHosts. Apparently, it's also not rock-solid, so let's
additionally consider consumer references on BareMetalHosts.
> OCPBUGS-5181: also use BMH.ConsumerRef for linking to master Machines

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/image_customization.go
- provisioning/image_customization_test.go
Ensure internal ironic traffic bypasses any proxies. The NO_PROXY value created in createImageCustomizationContainer is what IPA will end up using.
> OCPBUGS-5461: Add ironic IP to no_proxy

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/image_customization.go
- provisioning/image_customization_test.go
- provisioning/ironic_proxy.go
- provisioning/utils.go
We need to set the external url when
1. IPv6 is enabled
2. `VirtualMediaViaExternalNetwork` is enabled
When `VirtualMediaViaExternalNetwork` is enabled, ironic-proxy is also enabled.  This means that we can set the external url to be the IPv6 version of ironic-proxy.
In this patch, we
1.  Update openshift dependencies to gain access to `APIServerInternalIPs` (note the plural)
2.  Update the `GetIronicIP` function to `GetIronicIPs` (and `getServerInternalIP` to `getInternalIPs`), and thereby force all callers to deal with the dual stack scenario
3.  Pass both IPv4 and IPv6 IPs to ironic-proxy so it can listen to both (Ironic image patch forthcoming)
4. Set the external url only when the proxy and virtual media are enabled.
> OCPBUGS-4248: Set external Ironic URL to ironic-proxy IP

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/image_customization.go
- provisioning/image_customization_test.go
- provisioning/ironic_proxy.go
- provisioning/utils.go
Apparently, inspector has the same issue as ironic: there is
a possibility to hit an outdated URI.
As a result, both Ironic and Inspector are always reachable via
the API VIP. I hope nobody asks the same for the image server.
Requires:
- https://github.com/openshift/ironic-image/pull/355
- https://github.com/openshift/cluster-baremetal-operator/pull/335
> OCPBUGS-10343: use proxying for inspector in addition to ironic

- provisioning/baremetal_config.go
- provisioning/baremetal_config_test.go
- provisioning/baremetal_pod_test.go
The image server and Ironic use the same shared file system, there is
little sense to go through the TCP stack. Use a file:/// URL to avoid
spending time on downloading the image.
> Use a file URL for passing kernel to Ironic

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/ironic_proxy.go
- provisioning/utils.go
Apparently, inspector has the same issue as ironic: there is
a possibility to hit an outdated URI.
As a result, both Ironic and Inspector are always reachable via
the API VIP. I hope nobody asks the same for the image server.
Requires:
- https://github.com/openshift/ironic-image/pull/361
(cherry picked from commit 768b991bda3cf88dd7c4e789e0788e57b4ff2da8)
> [release-4.13] OCPBUGS-11985: use proxying for inspector in addition to ironic

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
The external url is the url the BMC will use to retrieve images from the httpd container inside metal3 in dual stack scenarios.
Each time the metal3 pod is started, we have to find any existing nodes, and rebuild the Ironic database.  During this process, we also tell each BMC where to get images.  This means that httpd doesn't have to be proxied, and therefore, when we construct the external url, we should ignore the ironic-proxy altogether.
This substantially changes the work done in https://github.com/openshift/cluster-baremetal-operator/pull/324.
> OCPBUGS-4248: Avoid ironic-proxy when setting external url

- controllers/provisioning_controller.go
- provisioning/baremetal_config.go
- provisioning/baremetal_config_test.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/bmo_pod.go
- provisioning/bmo_pod_test.go
- provisioning/utils.go
There is no reason to keep it tied to Ironic. Actually, it causes
constant chicken-and-egg problems where BMO needs to know the location
of Ironic.
> OCPBUGS-14064: Split baremetal-operator into a separate pod

- provisioning/baremetal_config.go
- provisioning/bmo_pod.go
- provisioning/bmo_pod_test.go
- provisioning/image_customization.go
- provisioning/state_service.go
- provisioning/utils.go
Using provisioning network addresses for communication between BMO and
Ironic seems to work but is a questionable design. Use the existing metal3-state
service instead.
Follow-up to c1bf1cba12c17990d43a15b4689189097f4f6116.
> OCPBUGS-15232: Use Service instead of provisioning IP for BMO to talk to Ironic

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/ironic_proxy.go
- provisioning/utils.go
Apparently, inspector has the same issue as ironic: there is
a possibility to hit an outdated URI.
As a result, both Ironic and Inspector are always reachable via
the API VIP. I hope nobody asks the same for the image server.
Requires:
- https://github.com/openshift/ironic-image/pull/385
(cherry picked from commit 768b991bda3cf88dd7c4e789e0788e57b4ff2da8)
> OCPBUGS-16169: use proxying for inspector in addition to ironic

- provisioning/bmo_pod.go
This is done for all pods and used to be done for BMO when it was a part
of the Metal3 pod.
> OCPBUGS-18059: Inject OpenShift CA and proxy information to BMO

- provisioning/utils.go
If PlatformStatus is nil return nil for APIServerInternalIPs
> OCPBUGS-17589: Guard against nil PlatformStatus

- provisioning/bmo_pod.go
baremetal-operator isn't listening on port 60000, the metrics listener is on port 8085 (the default), it dosn't need to be defined in the pod as we arn't using it. Defining a HostPort (even an unused one) will prevent the pod from being schedulable if the port is already in use on the host.
> OCPBUGS-18788: Remove metrics port from baremetal-operator

- provisioning/utils.go
If PlatformStatus is nil return nil for APIServerInternalIP
cherry-picked from 1e54596922e47b5c0153e8c3ce637fa45de7c066
Conflicts:
provisioning/utils.go
> OCPBUGS-19369: Guard against nil PlatformStatus

- controllers/provisioning_controller.go
- main.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_secrets.go
- provisioning/baremetal_secrets_test.go
When secret openshift-config/pull-secret changes, secret openshift-machine-api/pull-secret shall be updated. In order to achieve this:
* Add a new Watch to the ProvisioningReconciler.
* In method createRegistryPullSecret, recreate the secret in openshift-machine-api if it does not match the secret in openshift/config.
Spawn cluster with clusterbot:
~~~
launch openshift/cluster-baremetal-operator#352 ovn,metal
~~~
Modify secret openshift-config/pull-secret:
~~~
mkdir pull1
pushd pull1
oc extract secret/pull-secret -n openshift-config
vim .dockerconfigjson   # modify the pull-secret
oc create secret docker-registry --from-file .dockerconfigjson -n openshift-config pull-secret -o yaml --dry-run=true | oc apply -f -
popd
~~~
Check the log of the cluster-baremetal-operator-... pod, it should …
> Jira OCPBUGS-16919: Trigger reconcile if Secret openshift-config/pull-secret changes

- controllers/provisioning_controller.go
We start the BMO with or without the webhook based on the availability of the "service-ca" CO. We need to reconcile if it changes.
> OCPBUGS-17003: Trigger reconcile on service-ca CO

- config/profiles/default/manager_auth_proxy_patch.yaml
- manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
This commit adds the tls-cipher-suites to the baremetal-kube-rbac-proxy
> OCPBUGS-20563: Add tls-cipher-suites to baremetal-kube-rbac-proxy

- Dockerfile
- Makefile
When we build the image, the code has already been through code review, and CI.  Everything has been generated, and linted, and addressed.  At the build stage, we just want to compile the binary.
Furthermore, the golangci-lint program seems to require attention every time we upgrade Go in the builder.  This breaks the build, and we have to do emergency upgrades to get it unstuck.
> NO-ISSUE: Stop linting when building the image

- provisioning/baremetal_config_test.go
- provisioning/baremetal_pod.go
- provisioning/bmo_pod_test.go
- provisioning/image_customization.go
- provisioning/ironic_proxy.go
- provisioning/utils.go
IRONIC_EXTERNAL_URL_V6 is currently calculated incorrectly:
1) It uses the API VIP, but the Ironic's httpd is not proxied in the
same way as Ironic itself and thus may not be available there.
2) It uses an external IP even when a provisioning network is enabled
and VirtualMediaViaExternalNetwork is false.
This change fixes both issues, while also cleaning up the provisioning
utils to ensure all functions are dualstack-aware. The split between
the BMO and Metal3 pods is an implicit requirement of this change.
This change does NOT fix the fact that ICC is not configured correctly
for deploying IPv6-only nodes from a dualstack cluster.
> OCPBUGS-23131,OCPBUGS-23149: fix IRONIC_EXTERNAL_URL_V6

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
In 4.13, we cannot calculate pod IPs of the Metal3 pod to pass to BMO
since BMO is a part of this same pod. As a 4.13-only hack, pass
the variables to compose the external URL to BMO. Another 4.13-only
hack will build the URL out of them.
> OCPBUGS-23504: hack for deploying V6-only clusters from dualstack hubs

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
In 4.12, we cannot calculate pod IPs of the Metal3 pod to pass to BMO
since BMO is a part of this same pod. As a 4.12-only hack, pass
the variables to compose the external URL to BMO. Another 4.12-only
hack will build the URL out of them.
> OCPBUGS-23291: hack for deploying V6-only clusters from dualstack hubs

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
Upstream ironic-image is going to change the default to not use
inspector. To have control over the transition, enable inspector
explicitly for now.
> METAL-856: set USE_IRONIC_INSPECTOR explicitly

- config/cluster-baremetal-operator/cluster-baremetal-operator.yaml
- config/profiles/default/manager_auth_proxy_patch.yaml
- config/profiles/default/manager_webhook_patch.yaml
- manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
will improve visibility for reasons why a pod failed.
> OCPBUGS-28230: add terminationmessagepolicy to show last of error log in API

- provisioning/baremetal_pod.go
- provisioning/image_cache.go
- provisioning/image_customization.go
- provisioning/ironic_proxy.go
- provisioning/machine_os_images.go
Many of the containers we run have to be run in privileged mode in order to access a host volume - not only so they can write files as root, but also to get an SELinux context that allows it.
However, some containers currently running as privileged do not require this.
> OCPBUGS-27145: Reduce container privileges

- provisioning/baremetal_pod.go
- provisioning/image_customization.go
- provisioning/image_customization_test.go
This is needed to handle the case when single-stack spoke clusters are
deployed from a dual-stack hub.
While here, make sure to pass ports as part of the URLs. CBO is the
authority on port numbers, ICC should not hardcode them.
Requires:
- https://github.com/openshift/image-customization-controller/pull/120
> OCPBUGS-24579: pass all IPs to image-customization-controller

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
This commit includes the RBACs for the following resources:
- metal3.io/hostfirmwarecomponents + /status + /finalizers
- metal3.io/dataimages + /status + /finalizers (The controller is not yet merged upstream or downstream) see 
https://github.com/metal3-io/baremetal-operator/pull/1594
> METAL-979: Add RBAC for newer CRDs hostfirmwarecomponents and dataimages

- provisioning/baremetal_pod.go
- provisioning/bmo_pod.go
- provisioning/image_cache.go
- provisioning/image_customization.go
- provisioning/ironic_proxy.go
- provisioning/machine_os_images.go
found more.  This makes debugging via the API easier by attaching the last few kb of failed logs to pod status.
> OCPBUGS-28230: enforce termination message policy on all platform pods

- provisioning/baremetal_pod.go
- provisioning/image_cache.go
- provisioning/image_customization.go
- provisioning/ironic_proxy.go
- provisioning/machine_os_images.go
Some containers need to run privileged so that we can mount a hostPath volume, but we can at least drop the capabilites we don't need.
> OCPBUGS-27145: Drop unneccessary capabilities

- provisioning/bmo_pod.go
* ~Depends on https://github.com/metal3-io/baremetal-operator/pull/1725~
> OCPBUGS-33493: Enable leader election for baremetal-operator

- provisioning/baremetal_pod.go
Run metal3 containers as specific users and groups. This will fix permission issues with the ironic-inspector container that it gets when it tries to create a directory, resulting in its error state.
> OCPBUGS-32304: Run metal3 containers as specific users and groups

- provisioning/baremetal_pod.go
The /shared directory is mounted to the ironic, ironic-inspector, ramdisk-logs, dnsmasq, and httpd containers. As the ironic container creates the /shared directory, the ramdisk-logs container was unable to delete files from the directory as it was running as the ironic user and group, but the ironic container (which created and owned the files) was running in privileged mode. 
To resolve this issue, the metal3-ramdisk-logs container is now run with the privileged SecurityContext.
> OCPBUGS-35211: Add capability to metal3-ramdisk-logs container

- provisioning/baremetal_pod.go
> OCPBUGS-35503: Add capability to metal3-ramdisk-logs container

- provisioning/baremetal_config.go
- provisioning/baremetal_pod_test.go
getProvisioningIPCIDR now returns nil if ProvisioningNetwork is disabled. The external HostIP will then be used (as intended when the prov network is disabled).
> OCPBUGS-29660: Ignore provisioning ip config if disabled

- provisioning/baremetal_pod.go
- provisioning/image_customization.go
- provisioning/image_customization_test.go
> OCPBUGS-36285: Move pull secret from env var to VolumeMount in metal3-image-customization container

- provisioning/bmo_pod.go
[OCPBUGS-30919](https://issues.redhat.com/browse/OCPBUGS-30919)
Pin `metal3-baremetal-operator` pod to use the `hostnetwork-v2` SCC. This change resolves an issue where the operator pod was being assigned an incorrect SCC, causing it to get stuck in a CreateContainerConfigError state. 
Note for review: verify that the pod has the required SCC annotation by checking for the `openshift.io/required-scc: hostnetwork-v2` in the pod's metadata.
> OCPBUGS-30919: SCC-pinning for metal3-baremetal-operator

- controllers/provisioning_enabled.go
These platforms are supposed to be highly configurable.
> OCPBUGS-43371: allow all features on platform=none

- controllers/provisioning_controller.go
Replace the watches for CO and Proxy with actual Watches
Remove watches for machines for the time being
Readd watches for secrets
Readd the function to allow triggering reconciliation of
the provisioning CR as mapToProvisioningSingleton.
> OCPBUGS-36357: Replace watches with actual Watches

- controllers/provisioning_controller.go
Per Arbiter EP: https://github.com/openshift/enhancements/pull/1674
Adding a label or check for arbiter as well as master when the provisioning controller is looking to update the mac address for the machines.
> OCPEDGE-1607: feat: add arbiter node selector

- manifests/0000_31_cluster-baremetal-operator_07_clusteroperator.cr.yaml
This commit adds the missing relatedObjects to CBO
> [4.19] OCPBUGS-51275: add missing relatedObjects

- provisioning/image_customization.go
- provisioning/image_customization_test.go
The ICC will then add it to the custom image in order to pull down the IPA image.
> OCPBUGS-44839: Mount the user-ca-bundle into ICC

- go.mod
- go.sum
- vendor/golang.org/x/oauth2/README.md
- vendor/golang.org/x/oauth2/oauth2.go
- vendor/golang.org/x/oauth2/pkce.go
- vendor/golang.org/x/oauth2/token.go
- vendor/modules.txt
Steps used:
$ go get golang.org/x/oauth2@v0.27.0
$ go mod tidy
$ go mod vendor
> [4.19] OCPBUGS-52216: Bump x/oauth2 to 0.27.0

- provisioning/baremetal_config_test.go
The version I have locally is complaining about actualValue potentially
being nil because it does not consider t.Fatal to be, well, fatal.
Change the approach to using require.NotNil instead of a condition.
Follow-up to:
- https://github.com/openshift/cluster-baremetal-operator/pull/466
> NO-ISSUE: Silence a bogus error with newer golangci-lint

- Makefile
Contrary to the comment, it's not needed for the CI since the CI runs
manifest checks and linters separately.
> NO-ISSUE: Makefile: don't run all linters when running unit tests

- controllers/clusteroperator.go
Status ReasonResourceNotFound is not a fatal error, it's a temporary condition while the Metal3 pod does not exist yet.  Setting the operator's status as Degraded is wrong since nothing bad is happening. We set Degraded=False, Progressing=True, Available=False instead.
> OCPBUGS-56723: Treat ResourceNotFound as non-fatal

- controllers/clusteroperator.go
- controllers/clusteroperator_test.go
Currently, we log this even when the status is not actually new.
> OCPBUGS-57419: Do not log "new CO status" unnecessarily

- provisioning/bmo_pod.go
The webhookport should not be exposed on the host
> OCPBUGS-53392: Remove webhookport (9447) as HostPort

- provisioning/state_service.go
The current metal3-state service exposes different ports based on whether the proxy is enabled, port 6385 if without proxy, port 6388 (the private port) if with proxy.
Since port 6385 is exposed as a hostPort in both cases, there should always be a service exposing port 6385, regardless of the proxy configuration.
> OCPBUGS-60498: Always have a service for ironic-api port
