- controllers/provisioning_controller.go
- controllers/provisioning_controller_test.go
- hack/go-build.sh
- main.go
- vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
- vendor/k8s.io/client-go/testing/actions.go
- vendor/k8s.io/client-go/testing/fake.go
- vendor/k8s.io/client-go/testing/fixture.go
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
- vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Another step towards a minimally functioning operator to be deployed by CVO.
> Adding minimal logic to Reconcile method and setting up Scheme for future use

- Makefile
- hack/generate.sh
Add generate-check Makefile target to watch for updates to provisioning API CRD
> Add generate-check to watch for updates to provisioning API CRD

- Dockerfile
- Makefile
- hack/gen-crd.sh
- manifests/0000_30_cluster-baremetal-operator_00_metal3provisioning.crd.yaml
This PR takes care of installing properly, as requested by the CVO, the Provisioning CRD
> Install Provisioning CRD

- controllers/clusteroperator.go
- controllers/provisioning_controller.go
- go.sum
- main.go
Done as per request: https://github.com/openshift/cluster-baremetal-operator/pull/32#discussion_r500446673
> Add operandVersions to the ClusterOperator's Status

- OWNERS
This adds the bugzilla component information to the OWNERS file.
> Add Bugzilla Component Information

- OWNERS
Add asalkeld into reviewers pool in the repo. Sort the file alphabetically.
> Update owners file with addition of asalkeld

- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
This is matches openshift/enhancements#510 and doesn't change existing behavior
> add current profile annotations to CVO manifests

- controllers/provisioning_controller.go
- provisioning/baremetal_pod.go
Unblock updating of the metal3 Deployment created by the CBO (but not those originally created by the MAO - this will be added in future by #65).
> Enable Deployment updates

- controllers/provisioning_controller.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_secrets.go
- provisioning/baremetal_secrets_test.go
The companion to https://github.com/openshift/machine-api-operator/pull/727
> Turn on auth for ironic json-rpc

- controllers/provisioning_controller.go
- provisioning/baremetal_pod.go
When the metal3 Deployment was managed by the MAO, it used the Pod
labels `api=clusterapi` and `k8s-app=controller` to identify Metal³ as part
of the cluster API, and the `k8s-app=controller` label as the selector to
associate Pods with the Deployment. This was not only confusing, but
actually erroneous as the MAO also uses the same label as a selector for
its own Deployments of the Machine API controllers - this can
theoretically cause the separate Deployments to each try to manage both
sets of Pods matching the selector.
However, we cannot update the selector for an existing Deployment,
because that field is immutable. We also cannot (yet) delete the
existing Deployment because if, during an upgrade from OpenShift 4.6,
the MAO sees that it is missing then it will also try to recreate …
> Bug 1903717: Change default Deployment selector and handle downgrades

- provisioning/baremetal_pod.go
Add "api" label as one of the Labels in metal3 Deployment Pod
Template Spec because the metal3 Deployment created by MAO
uses LabelSelectors that are looking for this label on the Pod.
> Bug 1909527: Update Labels on the Pod TemplateSpec of the metal3 Deployment

- controllers/provisioning_controller.go
- provisioning/baremetal_pod.go
- provisioning/provisioning_info.go
Remove intermediate CO state when metal3 deployment is up but
the state of the Service and DaemonSet are still unknown.
> Bug 1913047: Remove intermediate CO progressing state

- provisioning/baremetal_pod.go
This is to support https://github.com/metal3-io/baremetal-operator/pull/797
> Add POD_NAMESPACE env variable to bmo container

- .golangci.yml
- controllers/provisioning_controller.go
- provisioning/baremetal_config_test.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/baremetal_secrets_test.go
- provisioning/container_images_test.go
Note the linter "nestif", prevents nested "ifs" and so encourages more readable code.
I have had to simplify the code in a couple of places, it shouldn't change anything logically.
> Add a couple more linters and fix some issues raised

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
This produces nicer looking Roles.
> Simplify the rbac roles under common groups if the verbs are the same

- controllers/provisioning_controller.go
- provisioning/baremetal_pod.go
- provisioning/provisioning_info.go
This PR:
1. Removes accommodations made to deal with upgrading a MAO created metal3 Pod
2. Deletes any old metal3 pod with old/incorrect Pod Selectors and create a new one with the correct ones
> Bug 1903700: Fix Pod Selectors in metal3 pods created by CBO

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
- provisioning/provisioning_info.go
Pass the SSHKey from install-config to the metal3
pod to allow ssh access to running IPA instances.
> Bug 1961226: Configure an IPA sshkey in the metal3 pod

- provisioning/baremetal_config_test.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
> Bug 1984576: Rebase of pull/177 (Pass MACs to set-static-ip initContainer) + unit tests

- manifests/0000_31_cluster-baremetal-operator_03_baremetalhost.crd.yaml
copy across the differences from bmo:release-4.7 BMH CRD.
> [release-4.7] bug 1976924: Update bmh crd

- README.md
- api/v1alpha1/provisioning_types.go
- hack/readme_inputs/main.go
> generate the ProvisioningSpec help in the README

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
This blocks https://github.com/openshift/baremetal-operator/pull/197
> Add RBAC for metal3.io/bmceventsubscriptions

- controllers/clusteroperator.go
Add the new resources to relatedObjects so that they will be picked up in must-gather
> Bug 2038196: Add new resources to relatedObjects

- provisioning/baremetal_webhook.go
- provisioning/baremetal_webhook_test.go
@ardaguclu Is this enough to enable it? Do I need to do anything else?
> Bug 2041510: Enable webhook for bmceventsubscriptions

- OWNERS
Remove asalkeld and kirankt from Owners
> Remove asalkeld and kirankt from Owners

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
We will need to read and modify them in image-customization-controller:
- https://github.com/openshift/image-customization-controller/pull/42
> Allow access to InfraEnv resources from assisted service

- manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
- manifests/image-references
- provisioning/container_images_test.go
- provisioning/sample_images.json
The registry name has been changed to machine-image-customization-controller
> Change registry reference for image customization controller image

- provisioning/image_customization_test.go
> Bug 2099928: Add UT for image_customization_test

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
This blocks https://github.com/openshift/baremetal-operator/pull/238
> Add RBAC for metal3.io/hardwaredata

- provisioning/utils.go
When a master abruptly terminates, a replacement will be found and a new
copy of the metal3 pod will be created. However, the old copy will be
left Terminating until the master comes back up or the pod is
force-deleted. This currently prevents the ICC deployment from being
updated since it expects only one copy of the pod. To work around this
problem, ignore pods with DeletionTimestamp when calculating the current
metal3 pod IP address.
> OCPBUGS-651: ignore metal3 pods that are terminating

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
See https://bugzilla.redhat.com/show_bug.cgi?id=2111675 for a long
discussion.
(cherry picked from commit 1f7c3788a3ff1cd2f7a9a9dbe07e1efaa3c7417b)
> OCPBUGS-1762: add a workaround for a NetworkManager issue

- controllers/provisioning_enabled.go
- controllers/provisioning_enabled_test.go
- provisioning/utils.go
> Enable running CBO from Azure

- controllers/provisioning_enabled.go
- controllers/provisioning_enabled_test.go
- provisioning/utils.go
> Enable running CBO from GCP

- provisioning/ironic_proxy.go
First and foremost, it made the proxy refer to itself, which only
happens to work when the API VIP is on the same master as the metal3
pod. Proxy must use the real pod IP.
The UPSTREAM_*_V6 variables do not exist in ironic-image, setting
them does nothing. On top of that, passing several upstream IPs does not
make much sense: we expect that Ironic is available on any of the valid
IPs, and we can make the proxy contact any of them.
This reverts commit ba7403e57e344e615d375af5cb7bfec5d56f03e9.
> Revert "proxy: pass ipv6 address to container"

- main.go
Set minimum TLS version for webhook to 1.2
> OCPBUGS-20572: Obsolete protocols for webhook

- main.go
In OCP, we tolerate about a minute of apiserver downtime before losing a lease by carefully setting the leader election values.  Combined with graceful lease release, this makes the default case fast, with a tolerant controller that doesnt' churn
> OCPBUGS-27760: Update the leader election durations to be tolerant

- provisioning/image_customization.go
- provisioning/image_customization_test.go
The assisted service needs to get the same configuration to embed IPA
into their images. Right now they embed CBO and ICC code to achieve
that. When we change anything on the CBO side (e.g. add ironic-proxy or
drop inspector), they need to update their code on all supported
releases.
This change adds a new secret with some of the IRONIC_* variables. It is
used for ICC itself and will be used by the assisted service instead of
CBO code directly.
> METAL-904: Move parts of ICC config to a new secret

- provisioning/baremetal_pod.go
> OCPBUGS-34041: Run metal3 containers as specific users and groups

- provisioning/baremetal_secrets.go
- vendor/github.com/openshift/api/annotations/annotations.go
- vendor/modules.txt
Make sure all TLS artifacts have clear ownership
> OCPBUGS-34649: provisioning: add ownership for tls secret

- controllers/provisioning_controller.go
Skip updateProvisioningMacAddresses in case the Machine CRD isn't registered
Remove Machine from the list of objects the provisioning controller manage
> METAL-1040: Allow CBO to run without MAPI

- provisioning/baremetal_pod.go
- provisioning/baremetal_pod_test.go
> OCPBUGS-36285: Mount htpasswds as volumeMounts in metal3-httpd container

- config/rbac/role.yaml
- controllers/provisioning_controller.go
- manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
Blocks https://github.com/openshift/baremetal-operator/pull/379
> METAL-982: Add HostUpdatePolicy RBAC

- README.md
Moving the information from an internal document.
> NO-ISSUE: document testing with custom images in README

- controllers/clusteroperator.go
Fixing  what @honza mentioned in  #461
> OCPBUGS-51275: Add new resources to controller relatedObjects

- provisioning/bmo_pod.go
- provisioning/bmo_pod_test.go
See also: https://github.com/metal3-io/baremetal-operator/pull/2477
> OCPBUGS-54965: Inform BMO when provisioning network is disabled

- provisioning/baremetal_config.go
- provisioning/baremetal_pod.go
- provisioning/baremetal_webhook.go
- provisioning/bmo_pod.go
- provisioning/container_images.go
- provisioning/image_cache.go
- provisioning/image_customization.go
- provisioning/ironic_proxy.go
- provisioning/machine_os_images.go
- provisioning/webhook.go
Also change an instance of io/ioutil to os as it just calls its function.
> METAL-1508: Change deprecated pointer to ptr
